name: Docker Image CI/CD # workflow名称，可以随意改
on: # workflow的事件钩子，告知程序说明时候出发自动部署
  push:
    branches: [release] # 在master分支有push操作的时候自动部署
jobs:
  build: # 打包并上传docker镜像
    runs-on: ubuntu-latest # 依赖的环境
    steps:
      - uses: actions/checkout@v2
      - name: Build Image
        run: |
          docker login --username=${{ secrets.ALI_ACCOUNT }} --password ${{ secrets.ALI_ACCOUNT_PWD }} registry.cn-beijing.aliyuncs.com
          docker build -t ${{ secrets.IMG_ADDRESS }}:$GITHUB_RUN_NUMBER .
          docker push ${{ secrets.IMG_ADDRESS }}:$GITHUB_RUN_NUMBER
          docker tag $(docker images ${{ secrets.IMG_ADDRESS }}:$GITHUB_RUN_NUMBER -q) ${{ secrets.IMG_ADDRESS }}:release
          docker push ${{ secrets.IMG_ADDRESS }}:release
